# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string
  repository_dispatch:
    types: [cms_update]

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build crealog
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          STORYBLOK_DELIVERY_API_TOKEN: pjxNJQkKufwy6QWQXazWVQtt
        run: |
          npm install --global pnpm
          pnpm install --config.dangerouslyAllowAllBuilds=true
          pnpm build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 86f46a87-c903-4298-84a6-0e148d1c20cd
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/crealog/config.yaml
          action: upload
